spring:
    kafka:
        properties:
            spring:
                json:
                    trusted:
                        packages: "*"
        consumer:
            bootstrap-servers: localhost:9092
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    data:
        mongodb:
            authentication-database: admin
            username: admin
            password: password
            database: library
            port: 27017
            host: localhost
            auto-index-creation: true
    application:
        name: book-service


server:
    port: 8888
